name: ktisma
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - types-pyyaml
  - pyyaml
  # Development tools
  - black
  - mypy
  - mypy_extensions
  - pylint
  - pyright
  # Testing
  - pytest
  - pytest-mock
  - pytest-cov
  - pytest-pylint
  # Documentation
  - sphinx
  - sphinxcontrib-napoleon
  - myst-parser
  - sphinx-rtd-theme
  - sphinx-needs
  - esbonio
variables:
