"""Generate minimal .latexmkrc shims for workspaces transitioning to ktisma.

Per roadmap: this adapter is optional, does not affect the core build path,
and does not read or parse existing .latexmkrc files.
"""

from __future__ import annotations

from pathlib import Path


LATEXMKRC_TEMPLATE = """\
# Generated by ktisma — transitional .latexmkrc shim
# This file redirects latexmk invocations to ktisma.
# Remove this file once your workflow calls ktisma directly.

# Ensure pdflatex mode by default
$pdf_mode = 1;

# Output directory matching ktisma defaults
$out_dir = '.ktisma_build/%STEM%';
"""


def generate_latexmkrc(workspace_root: Path, stem: str = "main") -> str:
    """Generate a transitional .latexmkrc shim content."""
    return LATEXMKRC_TEMPLATE.replace("%STEM%", stem)


def write_latexmkrc(workspace_root: Path, stem: str = "main") -> Path:
    """Write a transitional .latexmkrc to the workspace root.

    Returns the path of the written file.
    """
    content = generate_latexmkrc(workspace_root, stem)
    target = workspace_root / ".latexmkrc"
    target.write_text(content, encoding="utf-8")
    return target
